FROM jenkins/jenkins:lts

# Switch to root to install Python
USER root
RUN apt-get update && apt-get install -y python3 python3-pip python3-venv

# Switch back to the safe Jenkins user
USER jenkins
RUN jenkins-plugin-cli --plugins "git workflow-aggregator docker-workflow"