server {
    # Listen on the standard HTTP web port
    listen 80;

    location / {
        # Forward all traffic to the container named 'live-python-app' on port 5000
        proxy_pass http://live-python-app:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}